### PR TITLE
Add New Location Data & Japanese Translation & Fix some bus.

### PR DESCRIPTION
**Pull request by ALFEECLARE**
Mr. or Mrs. ate47
Thanks a lot for your mod providing.
I made some new function and fixed a bug.
I'm glad if you merge them.

1.Add new Location Data (Game Time, Biome Info, Looking Block Info, and so on)
2.Add Location Data hide Key.(Defalut: J)
3.Change Location Format MaxSize.(128 -> 256)
4.Add Japanese Translation File.
5.Fixed Bug: changes of  Location Data is not saved.

### CODE REVIEW

**Comment by ate47** [comment]
(you can call me ate47)

Even if commit names in English would have been better, the overall code is ok, I have a little question, why did you create a variable to switch the hud off, wouldn’t it be better to use the isShowMode() method from the location config with the setter to toggle it?

I will check the translation and it should be merged, if you can also add a regex matcher to not having to compute each location data it will be good, if you can post the same pull request for fabric and forge 1.18 it would be great

**Comment by ALFEECLARE** [comment]
ate47
>why did you create a variable to switch the hud off, wouldn’t it be better to use the isShowMode() method from the location config with the setter to toggle it?

Because when I displayed the vanilla debug mode(F3), it was hard to see because it was mixed with the HUD display. 
I think it would be convenient if it could be show/hidden with one key. 

>if you can also add a regex matcher to not having to compute each location data it will be good, 
>if you can post the same pull request for fabric and forge 1.18 it would be great

I mainly play in 1.17.1 + forge environment and haven't prepared any other environment yet.
So, I'll try it, but it will probably take a long time,

**Comment by ate47** [comment]
Can you check this PR I've made on your repo? https://github.com/ALFEECLARE/Xray/pull/1

It should fix the debug mode

**Comment by ALFEECLARE** [comment]
>Can you check this PR I've made on your repo? https://github.com/ALFEECLARE/Xray/pull/1

I'm sorry for being late.
I checked it, and merged your fixes.

>It should fix the debug mode

Sorry, It's too difficult for me....
I'm not used to making mods yet.

**Comment by ate47** [comment]
It was really good for a first time! I will need to add some code first, I will port the update to Fabric, then to 1.18 and I will upload it on CurseForge

**Comment by ALFEECLARE** [comment]
ate 47,

Thank you for your merging!
>I will port the update to Fabric, then to 1.18 and I will upload it on CurseForge.

I see. I'll try to fix for reduce calculation, and then test, & fix for Minecraft 1.18 + forge.
After them, I'll try to add Fabric version.(But it may be later than your fix.)

**Pull request merged**
