### PR TITLE
zh_cn

### PR DESCRIPTION
**Pull request by GodGun968**
Fixed some minor bugs

### CODE REVIEW

**Comment by ate47** [comment]
Next time, try to create only one commit instead of 5 to update one line. If you want a text edit, you can type `.` in a repository to get a vscode web editor.

**Comment by GodGun968** [comment]
okay

**Comment by GodGun968** [comment]
Besides looking messy, what are the other effects?

**Comment by ate47** [comment]
Here I was able to squash all the commits together because it was fitting in one commit, but if you wanted to update multiple things, I wouldn’t be able to squash them and it would be more annoying on your side.

Also if you want to merge again your branch from the 1.19 one you can’t and you should remove/recreate it or reset it.

**Comment by GodGun968** [comment]
I think you didn't see the other reply,it's about forge-1.17-v2 version can you give me a compiled file?

**Pull request merged**
