### PR TITLE
zh_cn

### PR DESCRIPTION
**Pull request by GodGun968**

### CODE REVIEW

**Comment by GodGun968** [comment]
for forge-1.17-v2

**Comment by GodGun968** [comment]
So can you give me a compiled file, otherwise I can't verify if my zh_cn is correct

**Comment by ate47** [comment]
You can compile the code using `./gradlew build`, you will then find the jar in the `build/libs` directory

**Comment by GodGun968** [comment]
Where should this code be entered

**Comment by ate47** [comment]
You can download the latest build jars [here](https://github.com/ate47/Xray/actions/runs/2554766712)

**Comment by GodGun968** [comment]
Thank you!

**Pull request merged**
